default:
	@echo " [DSTZ] bin/autotile.stz"
	@darnit-stringtable autotile ../bin/autotile.stz 2>/dev/null
	@echo " [CLDI] bin/char_gen.ldi"
	@darnit-fsimage char_gen ../bin/char_gen.ldi 2>/dev/null
clean:
